export type HiringStatus = "actively_hiring" | "selective" | "freeze" | "unknown";

export type IndiaLocation = {
  city: string;
  area?: string;
  lat: number;
  lng: number;
  headcount?: number;
};

export type GCC = {
  id: string;
  parentCompany: string;
  hqCountry: string;
  yearEstablishedInIndia: number;
  totalHeadcount: number;
  indiaLocations: IndiaLocation[];
  servicesFunctions: string[];
  leadership: { name: string; title: string }[];
  techStack: string[];
  hiringStatus: HiringStatus;
  website?: string;
  notes?: string;
};

export const GCCS: GCC[] = [
  {
    id: "microsoft-india",
    parentCompany: "Microsoft",
    hqCountry: "USA",
    yearEstablishedInIndia: 1990,
    totalHeadcount: 25000,
    indiaLocations: [
      { city: "Hyderabad", area: "Gachibowli", lat: 17.4435, lng: 78.3772, headcount: 12000 },
      { city: "Bengaluru", area: "Manyata Tech Park", lat: 13.0473, lng: 77.6207, headcount: 9000 },
      { city: "Noida", lat: 28.5355, lng: 77.391, headcount: 4000 },
    ],
    servicesFunctions: ["Cloud (Azure)", "AI/ML", "Productivity (M365)", "Gaming", "R&D", "Support"],
    leadership: [
      { name: "Puneet Chandok", title: "President, Microsoft India & South Asia" },
      { name: "Rajiv Kumar", title: "MD, Microsoft IDC" },
    ],
    techStack: ["Azure", "C#/.NET", "TypeScript", "Python", "Kubernetes", "PyTorch"],
    hiringStatus: "actively_hiring",
    website: "https://www.microsoft.com/en-in",
  },
  {
    id: "google-india",
    parentCompany: "Google",
    hqCountry: "USA",
    yearEstablishedInIndia: 2004,
    totalHeadcount: 10000,
    indiaLocations: [
      { city: "Bengaluru", area: "RMZ Ecoworld", lat: 12.9279, lng: 77.6271, headcount: 6000 },
      { city: "Hyderabad", area: "Gachibowli", lat: 17.4435, lng: 78.3772, headcount: 3000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 1000 },
    ],
    servicesFunctions: ["Search", "Ads", "Cloud (GCP)", "Android", "YouTube", "AI Research"],
    leadership: [
      { name: "Preeti Lobana", title: "VP & Country Manager, Google India" },
    ],
    techStack: ["Go", "Python", "C++", "Java", "TensorFlow", "Kubernetes", "BigQuery"],
    hiringStatus: "selective",
    website: "https://about.google/intl/en_in/",
  },
  {
    id: "amazon-india",
    parentCompany: "Amazon",
    hqCountry: "USA",
    yearEstablishedInIndia: 2004,
    totalHeadcount: 100000,
    indiaLocations: [
      { city: "Hyderabad", area: "HITEC City", lat: 17.4474, lng: 78.3762, headcount: 35000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 30000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 15000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 10000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 10000 },
    ],
    servicesFunctions: ["AWS", "Retail Tech", "Alexa", "Prime Video", "Devices", "Operations"],
    leadership: [
      { name: "Samir Kumar", title: "Country Manager, Amazon India" },
    ],
    techStack: ["Java", "Python", "AWS", "TypeScript", "React", "Rust"],
    hiringStatus: "actively_hiring",
    website: "https://www.amazon.in",
  },
  {
    id: "jpmorgan-chase-india",
    parentCompany: "JPMorgan Chase",
    hqCountry: "USA",
    yearEstablishedInIndia: 2002,
    totalHeadcount: 55000,
    indiaLocations: [
      { city: "Mumbai", area: "BKC", lat: 19.067, lng: 72.8686, headcount: 18000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 15000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 12000 },
      { city: "Mumbai", area: "Powai", lat: 19.1197, lng: 72.9051, headcount: 10000 },
    ],
    servicesFunctions: ["Investment Banking Tech", "Risk", "Compliance", "Asset Management", "Cybersecurity"],
    leadership: [
      { name: "Madhav Kalyan", title: "CEO, J.P. Morgan India" },
      { name: "Pari Natarajan", title: "Head of India Tech Centers" },
    ],
    techStack: ["Java", "Python", "AWS", "Kafka", "Spring Boot", "React"],
    hiringStatus: "actively_hiring",
    website: "https://www.jpmorgan.com/IN/en/about-us",
  },
  {
    id: "goldman-sachs-india",
    parentCompany: "Goldman Sachs",
    hqCountry: "USA",
    yearEstablishedInIndia: 2004,
    totalHeadcount: 9000,
    indiaLocations: [
      { city: "Bengaluru", area: "Outer Ring Road", lat: 12.9352, lng: 77.6245, headcount: 8000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 1000 },
    ],
    servicesFunctions: ["Engineering", "Risk", "Operations", "Asset Management", "Research"],
    leadership: [
      { name: "Gunjan Samtani", title: "Head of Goldman Sachs Services India" },
    ],
    techStack: ["Java", "Python", "Slang", "kdb+", "AWS"],
    hiringStatus: "selective",
    website: "https://www.goldmansachs.com",
  },
  {
    id: "morgan-stanley-india",
    parentCompany: "Morgan Stanley",
    hqCountry: "USA",
    yearEstablishedInIndia: 1993,
    totalHeadcount: 12000,
    indiaLocations: [
      { city: "Mumbai", area: "Goregaon", lat: 19.1646, lng: 72.8493, headcount: 6000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 6000 },
    ],
    servicesFunctions: ["Investment Banking Tech", "Wealth Management", "Risk", "Operations"],
    leadership: [{ name: "Sanjay Shah", title: "Head of Morgan Stanley India Services" }],
    techStack: ["Java", "Python", "Scala", "AWS", "React"],
    hiringStatus: "selective",
  },
  {
    id: "wells-fargo-india",
    parentCompany: "Wells Fargo",
    hqCountry: "USA",
    yearEstablishedInIndia: 2006,
    totalHeadcount: 45000,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 18000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 17000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 10000 },
    ],
    servicesFunctions: ["Banking Tech", "Risk", "Compliance", "Data & Analytics", "Operations"],
    leadership: [{ name: "Shankar Sadasivam", title: "Head of Wells Fargo India" }],
    techStack: ["Java", "Python", "AWS", "Snowflake", "Kafka"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "citi-india-solutions-center",
    parentCompany: "Citi",
    hqCountry: "USA",
    yearEstablishedInIndia: 2004,
    totalHeadcount: 30000,
    indiaLocations: [
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 9000 },
      { city: "Mumbai", lat: 19.076, lng: 72.8777, headcount: 8000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 7000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 6000 },
    ],
    servicesFunctions: ["Banking Tech", "Operations", "Risk", "Markets Tech"],
    leadership: [{ name: "Ashu Khullar", title: "CEO, Citi India" }],
    techStack: ["Java", "Python", "AWS", "Oracle", "Kafka"],
    hiringStatus: "selective",
  },
  {
    id: "deutsche-bank-india",
    parentCompany: "Deutsche Bank",
    hqCountry: "Germany",
    yearEstablishedInIndia: 2003,
    totalHeadcount: 18000,
    indiaLocations: [
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 8000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 5000 },
      { city: "Mumbai", lat: 19.076, lng: 72.8777, headcount: 3000 },
      { city: "Jaipur", lat: 26.9124, lng: 75.7873, headcount: 2000 },
    ],
    servicesFunctions: ["Investment Banking Tech", "Risk", "Compliance", "Operations"],
    leadership: [{ name: "Dilipkumar Khandelwal", title: "CEO, DB Tech Centres" }],
    techStack: ["Java", "Python", "GCP", "Scala", "React"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "barclays-india",
    parentCompany: "Barclays",
    hqCountry: "UK",
    yearEstablishedInIndia: 2006,
    totalHeadcount: 24000,
    indiaLocations: [
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 12000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 6000 },
      { city: "Noida", lat: 28.5355, lng: 77.391, headcount: 6000 },
    ],
    servicesFunctions: ["Investment Banking Tech", "Cards", "Risk", "Operations"],
    leadership: [{ name: "Rahul Pradhan", title: "Head of BGSC India" }],
    techStack: ["Java", "Python", "AWS", "Kafka", "React"],
    hiringStatus: "selective",
  },
  {
    id: "hsbc-india",
    parentCompany: "HSBC",
    hqCountry: "UK",
    yearEstablishedInIndia: 2002,
    totalHeadcount: 39000,
    indiaLocations: [
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 12000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 10000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 8000 },
      { city: "Kolkata", lat: 22.5726, lng: 88.3639, headcount: 5000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 4000 },
    ],
    servicesFunctions: ["Retail Banking Tech", "Wealth", "Risk", "Operations"],
    leadership: [{ name: "Hitendra Dave", title: "CEO, HSBC India" }],
    techStack: ["Java", "Python", "GCP", "Snowflake", "Kafka"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "shell-india",
    parentCompany: "Shell",
    hqCountry: "UK / Netherlands",
    yearEstablishedInIndia: 2007,
    totalHeadcount: 11000,
    indiaLocations: [
      { city: "Bengaluru", area: "RMZ Ecoworld", lat: 12.9279, lng: 77.6271, headcount: 6500 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 4500 },
    ],
    servicesFunctions: ["Energy R&D", "Digital", "Trading Tech", "Engineering"],
    leadership: [{ name: "Mansi Tripathy", title: "Country Chair, Shell India" }],
    techStack: ["Python", "Azure", "Databricks", "Java", "C++"],
    hiringStatus: "selective",
  },
  {
    id: "target-india",
    parentCompany: "Target",
    hqCountry: "USA",
    yearEstablishedInIndia: 2005,
    totalHeadcount: 4500,
    indiaLocations: [
      { city: "Bengaluru", area: "Manyata Tech Park", lat: 13.0473, lng: 77.6207, headcount: 4500 },
    ],
    servicesFunctions: ["Retail Tech", "Supply Chain", "Data Science", "Marketing Tech"],
    leadership: [{ name: "Bharath Madhusudan", title: "President, Target in India" }],
    techStack: ["Java", "Kotlin", "Python", "GCP", "React"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "walmart-global-tech-india",
    parentCompany: "Walmart",
    hqCountry: "USA",
    yearEstablishedInIndia: 2007,
    totalHeadcount: 7000,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 5500 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 1500 },
    ],
    servicesFunctions: ["E-commerce", "Supply Chain", "Marketplace Tech", "Data Science"],
    leadership: [{ name: "Hari Vasudev", title: "CTO, Walmart US & Head of WGT India" }],
    techStack: ["Java", "Node.js", "Azure", "Kafka", "React", "Python"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "lowes-india",
    parentCompany: "Lowe's",
    hqCountry: "USA",
    yearEstablishedInIndia: 2014,
    totalHeadcount: 4500,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 4500 },
    ],
    servicesFunctions: ["Retail Tech", "Supply Chain", "Pro Tech", "Data Science"],
    leadership: [{ name: "Ankur Mittal", title: "Managing Director, Lowe's India" }],
    techStack: ["Java", "Python", "GCP", "React", "Kafka"],
    hiringStatus: "selective",
  },
  {
    id: "sap-labs-india",
    parentCompany: "SAP",
    hqCountry: "Germany",
    yearEstablishedInIndia: 1998,
    totalHeadcount: 15000,
    indiaLocations: [
      { city: "Bengaluru", area: "Whitefield", lat: 12.9698, lng: 77.7499, headcount: 10000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 3000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 1500 },
      { city: "Mumbai", lat: 19.076, lng: 72.8777, headcount: 500 },
    ],
    servicesFunctions: ["ERP R&D", "S/4HANA", "Cloud", "AI"],
    leadership: [{ name: "Sindhu Gangadharan", title: "MD, SAP Labs India" }],
    techStack: ["ABAP", "Java", "JavaScript", "HANA", "Kubernetes"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "siemens-india",
    parentCompany: "Siemens",
    hqCountry: "Germany",
    yearEstablishedInIndia: 1990,
    totalHeadcount: 10000,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 4000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 3000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 2000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 1000 },
    ],
    servicesFunctions: ["Industrial Software", "Digital Industries", "Mobility", "Healthineers Tech"],
    leadership: [{ name: "Sunil Mathur", title: "MD & CEO, Siemens India" }],
    techStack: ["C++", "Java", "Python", "Azure", "ROS"],
    hiringStatus: "selective",
  },
  {
    id: "bosch-india",
    parentCompany: "Robert Bosch",
    hqCountry: "Germany",
    yearEstablishedInIndia: 1951,
    totalHeadcount: 38000,
    indiaLocations: [
      { city: "Bengaluru", area: "Koramangala", lat: 12.9352, lng: 77.6146, headcount: 22000 },
      { city: "Coimbatore", lat: 11.0168, lng: 76.9558, headcount: 8000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 4000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 4000 },
    ],
    servicesFunctions: ["Automotive R&D", "IoT", "Industrial", "Mobility Software"],
    leadership: [{ name: "Guruprasad Mudlapur", title: "President, Bosch Group India" }],
    techStack: ["C++", "Python", "AUTOSAR", "AWS", "ROS", "MATLAB"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "cisco-india",
    parentCompany: "Cisco Systems",
    hqCountry: "USA",
    yearEstablishedInIndia: 1995,
    totalHeadcount: 11000,
    indiaLocations: [
      { city: "Bengaluru", area: "Cessna Business Park", lat: 12.9551, lng: 77.7016, headcount: 9000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 1500 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 500 },
    ],
    servicesFunctions: ["Networking R&D", "Security", "Webex", "Cloud"],
    leadership: [{ name: "Daisy Chittilapilly", title: "President, Cisco India & SAARC" }],
    techStack: ["C", "C++", "Go", "Python", "Kubernetes"],
    hiringStatus: "selective",
  },
  {
    id: "ibm-india",
    parentCompany: "IBM",
    hqCountry: "USA",
    yearEstablishedInIndia: 1992,
    totalHeadcount: 130000,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 45000 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 25000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 20000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 15000 },
      { city: "Kolkata", lat: 22.5726, lng: 88.3639, headcount: 10000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 15000 },
    ],
    servicesFunctions: ["Consulting", "Software (Red Hat)", "Cloud", "Research"],
    leadership: [{ name: "Sandip Patel", title: "MD, IBM India & South Asia" }],
    techStack: ["Java", "Python", "OpenShift", "Watson", "Go"],
    hiringStatus: "selective",
  },
  {
    id: "salesforce-india",
    parentCompany: "Salesforce",
    hqCountry: "USA",
    yearEstablishedInIndia: 2005,
    totalHeadcount: 12500,
    indiaLocations: [
      { city: "Bengaluru", area: "Embassy GolfLinks", lat: 12.9608, lng: 77.6469, headcount: 6000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 5000 },
      { city: "Mumbai", lat: 19.076, lng: 72.8777, headcount: 1000 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 500 },
    ],
    servicesFunctions: ["CRM R&D", "Slack", "AI (Einstein)", "Marketing Cloud"],
    leadership: [{ name: "Arundhati Bhattacharya", title: "Chairperson & CEO, Salesforce India" }],
    techStack: ["Java", "Apex", "JavaScript", "AWS", "Heroku"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "uber-india",
    parentCompany: "Uber",
    hqCountry: "USA",
    yearEstablishedInIndia: 2015,
    totalHeadcount: 4000,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 2500 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 1500 },
    ],
    servicesFunctions: ["Mobility R&D", "Eats", "Maps", "Driver Platform"],
    leadership: [{ name: "Prabhjeet Singh", title: "President, Uber India & South Asia" }],
    techStack: ["Go", "Java", "Python", "AWS", "Kafka"],
    hiringStatus: "selective",
  },
  {
    id: "intel-india",
    parentCompany: "Intel",
    hqCountry: "USA",
    yearEstablishedInIndia: 1988,
    totalHeadcount: 15000,
    indiaLocations: [
      { city: "Bengaluru", area: "SRR4 Campus", lat: 12.8456, lng: 77.6603, headcount: 13000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 2000 },
    ],
    servicesFunctions: ["Silicon Design", "Software", "Foundry", "AI"],
    leadership: [{ name: "Gokul Subramaniam", title: "President, Intel India" }],
    techStack: ["Verilog", "C++", "Python", "SystemC", "Linux"],
    hiringStatus: "selective",
  },
  {
    id: "qualcomm-india",
    parentCompany: "Qualcomm",
    hqCountry: "USA",
    yearEstablishedInIndia: 1996,
    totalHeadcount: 12000,
    indiaLocations: [
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 6000 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 5000 },
      { city: "Chennai", lat: 13.0827, lng: 80.2707, headcount: 1000 },
    ],
    servicesFunctions: ["Modem", "Snapdragon SoC", "Wireless R&D", "AI"],
    leadership: [{ name: "Savi Soin", title: "President, Qualcomm India" }],
    techStack: ["Verilog", "C++", "Python", "Linux"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "nvidia-india",
    parentCompany: "NVIDIA",
    hqCountry: "USA",
    yearEstablishedInIndia: 2004,
    totalHeadcount: 4500,
    indiaLocations: [
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 2000 },
      { city: "Hyderabad", lat: 17.385, lng: 78.4867, headcount: 1500 },
      { city: "Pune", lat: 18.5204, lng: 73.8567, headcount: 600 },
      { city: "Gurugram", lat: 28.4595, lng: 77.0266, headcount: 400 },
    ],
    servicesFunctions: ["GPU Architecture", "AI/Deep Learning", "DGX", "Drive"],
    leadership: [{ name: "Vishal Dhupar", title: "MD, NVIDIA South Asia" }],
    techStack: ["CUDA", "C++", "Python", "PyTorch", "Verilog"],
    hiringStatus: "actively_hiring",
  },
  {
    id: "adobe-india",
    parentCompany: "Adobe",
    hqCountry: "USA",
    yearEstablishedInIndia: 1998,
    totalHeadcount: 7500,
    indiaLocations: [
      { city: "Noida", area: "Sector 132", lat: 28.5142, lng: 77.405, headcount: 4500 },
      { city: "Bengaluru", lat: 12.9716, lng: 77.5946, headcount: 3000 },
    ],
    servicesFunctions: ["Creative Cloud", "Document Cloud", "Experience Cloud", "AI (Sensei/Firefly)"],
    leadership: [{ name: "Prativa Mohapatra", title: "VP & MD, Adobe India" }],
    techStack: ["C++", "Java", "Python", "AWS", "React"],
    hiringStatus: "selective",
  },
];
